#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. "${WM_PROJECT_DIR:?}"/bin/tools/CleanFunctions    # Tutorial clean functions
#------------------------------------------------------------------------------


foamListTimes -rm
rm -rf log.blockMesh
rm -rf log.waveFoam
rm -rf log.checkMesh
rm -rf case.foam
#rm -rf processor0
#rm -rf processor1
#rm -rf processor2
#rm -rf processor3


echo "Case cleaned!"

#------------------------------------------------------------------------------


