#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. "${WM_PROJECT_DIR:?}"/bin/tools/CleanFunctions    # Tutorial clean functions
#------------------------------------------------------------------------------


foamListTimes -rm
rm -rf log.blockMesh
rm -rf log.icoFoam
rm -rf log.checkMesh
rm -rf cavity.foam

echo "Case cleaned!"

#------------------------------------------------------------------------------


