#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. "${WM_PROJECT_DIR:?}"/bin/tools/CleanFunctions    # Tutorial clean functions
#------------------------------------------------------------------------------

cleanCase
rm -rf constant/polyMesh
rm -rf constant/triSurface
rm -rf constant/extendedFeatureEdgeMesh
rm -rf 0/cellLevel
rm -rf 0/pointLevel
rm -f naca0012.stl

echo "Case cleaned!"

#------------------------------------------------------------------------------
