#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. "${WM_PROJECT_DIR:?}"/bin/tools/CleanFunctions    # Tutorial clean functions
#------------------------------------------------------------------------------


foamListTimes -rm
rm -rf log.blockMesh
rm -rf log.laplacianFoam
rm -rf log.checkMesh
rm -rf 2DConduction.foam

echo "Case cleaned!"

#------------------------------------------------------------------------------


